services:
  php-symfo:
    build:
      context: ./php-symfo
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    volumes:
      - .:/var/www/html

  mailer:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/db_data:rw

volumes:
  db_data:

